#!/usr/bin/env bash

set -eu

# Build and optimise wasm

rustc "-C" "debuginfo=0" "-C" "opt-level=s" "--target=wasm32-unknown-unknown" "--crate-type" "cdylib" $@

for wasm in $(find /playground-result/ -name '*wasm'); do
    wasm-strip "${wasm}"
done
